### PR TITLE
Matlab update

### PR DESCRIPTION
**Pull request by abaillod**
I updated the matlab tools with my own subroutines. I did some cleanup, and added the routine "SPEC_Namelist" which allows you to read, edit, and write SPEC input files, as well as plot the initial guess.

I think it is safe to merge, since I didn't touch SPEC source, only the matlab tools. Let me know if you find a bug or if a feature is missing!

### CODE REVIEW

**Comment by jloizu** [comment]
I started testing these updated tools. 

- I think there is a bug in get_spec_jacobian.m, line 26, what is "<<<<<<< HEAD"? This gives errors.
- Could you explain how to use the SPEC_Namelist? why is it in some other directory (and inside that, there are also other directories with other routines...a bit confusing to me, sorry!)

**Comment by abaillod** [comment]
Thanks for testing!

I don't see the problematic line you are talking about in `get_spec_jacobian.m`. In the latest version of the matlab_update branch, line 26 is https://github.com/PrincetonUniversity/SPEC/blob/1e6331f0de3539ab46ad73c3e824f0a31447ce3d/Utilities/matlabtools/get_spec_jacobian.m#L25-L32

Regarding the SPEC_Namelist; you can just do

```
nm = SPEC_Namelist('input.sp')
```

Then you can do `nm.` and double tabs to see all methods associated to SPEC_Namelist. Use the help to print some information about each element of the class:

```
>> nm = SPEC_Namelist('final.sp');
>> nm.
change_boundary_representation  lists                           plot_initial_guess              truncate_fourier_series         
diagnosticslist                 locallist                       plot_plasma_boundary            write_input_file                
get_fourier_harmonics           numericlist                     read_initial_guess              
globallist                      physicslist                     screenlist                      
initial_guess                   plot_computational_boundary     set_fourier_harmonics           
>> help nm.truncate_fourier_series
--- help for SPEC_Namelist/truncate_fourier_series ---

 
  TRUNCATE_FOURIER_SERIES( MPOL, NTOR )
  =====================================
 
  Truncates all spectral quantities to the requested poloidal
  and toroidal resolution
 
  INPUTS
  ------
    -Mpol: Poloidal resolution
    -Ntor: Toroidal resolution
 
  OUTPUT
  ------
    -OBJ: Truncated instance of SPEC_Namelist
```

I should probably write a tutorial for this class; I will write one down this week.

**Comment by jloizu** [comment]
OK the problem with the jacobian was related to internal file conflicts I had not resolved myself. 

One small issue: the routine plot_spec_poincare.m is not consistent between arguments and help – please explain in the help what is varargin.

**Comment by abaillod** [comment]
I pushed a new commit.

* I cleaned up the SPEC_Namelist directory, there is now only the matlab class and the read / write routine for FORTRAN namelists.
* I fixed a typo with `get_spec_regularisation_factor`
* I extended the description of `plot_spec_poincare` to explain what varargin is. 

Regarding your error in `plot_spec_modB_boundary`, I don't have it. Is it possible that you have another internal file conflict?

**Comment by jloizu** [comment]
OK so my internal conflicts were finally solved (thanks!). 

I found some bugs in a number of routines, and fixed them, and pushed changes – please check.

Doxygen automatic testing seems to fail  – please have a look.

After that, we'll be almost ready to merge!

**Comment by jonathanschilling** [comment]
@jloizu 
I fixed the doxygen version in the master branch, but currently it fails due to some "$" in the comments which confuse LaTeX when generating the PDF version of the documentation.

**Comment by abaillod** [comment]
Sorry this thing completely got out of my mind.

I tested most of the plotting routines and everything seems to be fine on my side. I vote for a merge!

**Comment by zhisong** [comment]
Does anyone know what happens to the cmake tests? They seem to fail since 4 months ago.

**Comment by jonathanschilling** [comment]
> Does anyone know what happens to the cmake tests? They seem to fail since 4 months ago.

Seems due to pip being to old on the provided docker image (see https://stackoverflow.com/a/63457606). Fixed now.

**Comment by jonathanschilling** [comment]
> I vote for a merge!

Me too :-)

**Comment by smiet** [comment]
There seemed widespread agreement on merging this with master, but this was never completed. 
I am re-triggering the checks and waiting for 24 hours, if nobody objects, I will merge this into master.

**Pull request merged**
