### PR TITLE
Readme 404 fix

### PR DESCRIPTION
**Pull request by missing-user**
Suggested fix for https://github.com/PrincetonUniversity/SPEC/issues/205 the broken URLs in the readme. 
- Added the citations file
- Generally cleaned up the README a bit, added headings and the SPEC logo
- Also made minor fixes related to the doxygen grouping, where some routines that produce hidden files weren't part of grp_output , were lacking doxygen params, etc...

### CODE REVIEW

**Review by jons-pf — APPROVED** [review]

**Comment by smiet** [comment]
Thank you so much!

I see that there On the issue there were a few requests: 
-> separate the references into the citelist, containing only 
- https://iopscience.iop.org/article/10.1088/0741-3335/54/1/014005
- https://iopscience.iop.org/article/10.1088/1361-6587/ab9a61/meta

-> and a biblography with the other papers ("A list of publications using SPEC are in our [bibliography section](https://princetonuniversity.github.io/SPEC/citelist)"
- https://doi.org/10.1063/1.4967709
- https://doi.org/10.1017/S0022377821000520
- https://doi.org/10.1063/1.4944818
- https://doi.org/10.1063/1.4931094
- https://doi.org/10.1063/1.4906888
- https://doi.org/10.1063/5.0009110
- https://doi.org/10.1017/S0022377823000934
- https://doi.org/10.1017/S0022377817000861
- https://doi.org/10.1017/S0022377823000910
- https://doi.org/10.1063/1.5091765
- https://dx.doi.org/10.1088/1741-4326/ad39d9

And link to it. 

Warmest regards, 
   Chris

**Comment by smiet** [comment]
Sorry, not familiar with .cff file handling, but the actions are giving an error: 

```
 ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 106, column 12
```

**Comment by missing-user** [comment]
> Sorry, not familiar with .cff file handling, but the actions are giving an error:
> 
> ```
>  ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context
>   in "<unicode string>", line 106, column 12
> ```

I must have accidentally deleted a space before committing. Should be fine now :)

**Review by smiet — APPROVED** [review]
Thanks for the work!

**Pull request merged**
